language: node_js
node_js:
  - 15
addons:
  apt:
    packages:
      # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves
      - libgconf-2-4
cache:
  # Caches $HOME/.npm when npm ci is default script command
  # Caches node_modules in all other cases
  yarn: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.10
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - cd api && yarn install --frozen-lockfile
  - cd ../client && yarn install --frozen-lockfile
script:
  - yarn run start_and_test